version: '2.4'
services:
  wildfly1:
    build: ./wildfly
    container_name: wildfly-1
    ports:
      - '8180:8080'
      - '9991:9990'
      - '8787:8787'
    # cpus: '2'
    environment:
      - APPFORMER_JMS_MODE=REMOTE
      - 'APPFORMER_JMS_URL="tcp://artemis:61616?ha=true&retryInterval=1000&retryIntervalMultiplier=1.0&reconnectAttempts=-1"'
      - APPFORMER_JMS_USERNAME=admin
      - APPFORMER_JMS_PASSWORD=admin
      - METADATA_INDEX=infinispan
      - METADATA_PORT=11222
      - METADATA_HOST=infinispan
    volumes:
      - './wildfly/deployments1:/opt/jboss/wildfly/standalone/deployments'
      - './nfs/niogit1/.niogit:/opt/jboss/.niogit:rw'
      - './nfs/niogit1/.kie-wb-playground:/opt/jboss/.kie-wb-playground:rw'
    links:
      - infinispan
      - artemis
  wildfly2:
    build: ./wildfly
    container_name: wildfly-2
    ports:
      - '8280:8080'
      - '9992:9990'
      - '8788:8787'
    # cpus: '2'
    environment:
      - APPFORMER_JMS_MODE=REMOTE
      - 'APPFORMER_JMS_URL="tcp://artemis:61616?ha=true&retryInterval=1000&retryIntervalMultiplier=1.0&reconnectAttempts=-1"'
      - APPFORMER_JMS_USERNAME=admin
      - APPFORMER_JMS_PASSWORD=admin
      - METADATA_INDEX=infinispan
      - METADATA_PORT=11222
      - METADATA_HOST=infinispan
    volumes:
      - './wildfly/deployments2:/opt/jboss/wildfly/standalone/deployments'
      - './nfs/niogit2/.niogit:/opt/jboss/.niogit:rw'
      - './nfs/niogit2/.kie-wb-playground:/opt/jboss/.kie-wb-playground:rw'
    links:
      - infinispan
      - artemis 
  infinispan:
    image: 'jboss/infinispan-server:9.4.11.Final'
    container_name: infinispa
    environment:
      - APP_USER=user
      - APP_PASS=user
    ports:
      - '11222:11222'
      - '8380:8080'
  artemis:
    image: vromero/activemq-artemis
    container_name: artemis
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - '61616:61616'
      - '8161:8161'
